/*
 * This file was automatically generated by EvoSuite
 * Mon May 31 17:57:02 GMT 2021
 */

package org.jfree.chart.axis;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jfree.chart.api.RectangleEdge;
import org.jfree.chart.axis.Axis;
import org.jfree.chart.axis.AxisCollection;
import org.jfree.chart.axis.CyclicNumberAxis;
import org.jfree.chart.axis.ExtendedCategoryAxis;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.plot.ThermometerPlot;
import org.jfree.data.general.DefaultValueDataset;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AxisCollection_ESTest extends AxisCollection_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AxisCollection axisCollection0 = new AxisCollection();
      DefaultValueDataset defaultValueDataset0 = new DefaultValueDataset(0.0);
      ThermometerPlot thermometerPlot0 = new ThermometerPlot(defaultValueDataset0);
      ValueAxis valueAxis0 = thermometerPlot0.getRangeAxis();
      RectangleEdge rectangleEdge0 = RectangleEdge.RIGHT;
      axisCollection0.add(valueAxis0, rectangleEdge0);
      List<Axis> list0 = axisCollection0.getAxesAtRight();
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AxisCollection axisCollection0 = new AxisCollection();
      ExtendedCategoryAxis extendedCategoryAxis0 = new ExtendedCategoryAxis("r@@>w&7#Cpkz\"UZ");
      RectangleEdge rectangleEdge0 = RectangleEdge.LEFT;
      axisCollection0.add(extendedCategoryAxis0, rectangleEdge0);
      List<Axis> list0 = axisCollection0.getAxesAtLeft();
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AxisCollection axisCollection0 = new AxisCollection();
      ThermometerPlot thermometerPlot0 = new ThermometerPlot();
      ValueAxis valueAxis0 = thermometerPlot0.getRangeAxis();
      RectangleEdge rectangleEdge0 = RectangleEdge.BOTTOM;
      axisCollection0.add(valueAxis0, rectangleEdge0);
      List<Axis> list0 = axisCollection0.getAxesAtBottom();
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AxisCollection axisCollection0 = new AxisCollection();
      RectangleEdge rectangleEdge0 = RectangleEdge.TOP;
      // Undeclared exception!
      try { 
        axisCollection0.add((Axis) null, rectangleEdge0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Null 'axis' argument.
         //
         verifyException("org.jfree.chart.internal.Args", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      AxisCollection axisCollection0 = new AxisCollection();
      CyclicNumberAxis cyclicNumberAxis0 = new CyclicNumberAxis((-3270.31380115526), (-3270.31380115526));
      RectangleEdge rectangleEdge0 = RectangleEdge.TOP;
      axisCollection0.add(cyclicNumberAxis0, rectangleEdge0);
      List<Axis> list0 = axisCollection0.getAxesAtTop();
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      AxisCollection axisCollection0 = new AxisCollection();
      List<Axis> list0 = axisCollection0.getAxesAtBottom();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      AxisCollection axisCollection0 = new AxisCollection();
      List<Axis> list0 = axisCollection0.getAxesAtTop();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      AxisCollection axisCollection0 = new AxisCollection();
      List<Axis> list0 = axisCollection0.getAxesAtRight();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      AxisCollection axisCollection0 = new AxisCollection();
      List<Axis> list0 = axisCollection0.getAxesAtLeft();
      assertTrue(list0.isEmpty());
  }
}
