/*
 * This file was automatically generated by EvoSuite
 * Mon May 31 18:07:43 GMT 2021
 */

package org.jfree.chart.entity;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Polygon;
import java.awt.Rectangle;
import java.awt.Shape;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jfree.chart.entity.ChartEntity;
import org.jfree.chart.imagemap.DynamicDriveToolTipTagFragmentGenerator;
import org.jfree.chart.imagemap.OverLIBToolTipTagFragmentGenerator;
import org.jfree.chart.imagemap.StandardToolTipTagFragmentGenerator;
import org.jfree.chart.imagemap.StandardURLTagFragmentGenerator;
import org.jfree.chart.imagemap.ToolTipTagFragmentGenerator;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ChartEntity_ESTest extends ChartEntity_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Rectangle2D.Double rectangle2D_Double0 = new Rectangle2D.Double((-1323.144935), 1177.98, 494.3609, (-1323.144935));
      ChartEntity chartEntity0 = new ChartEntity(rectangle2D_Double0);
      String string0 = chartEntity0.getShapeCoords();
      assertEquals("-1323,1177,-829,-146", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Line2D.Double line2D_Double0 = new Line2D.Double((-24.96235714836), (-24.96235714836), (-24.96235714836), (-24.96235714836));
      ChartEntity chartEntity0 = new ChartEntity(line2D_Double0);
      String string0 = chartEntity0.getURLText();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Line2D.Double line2D_Double0 = new Line2D.Double(2859.16822, 2859.16822, 2859.16822, (-1.0));
      ChartEntity chartEntity0 = new ChartEntity(line2D_Double0);
      String string0 = chartEntity0.getToolTipText();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Point point0 = new Point(218, 767);
      Rectangle rectangle0 = new Rectangle(point0);
      ChartEntity chartEntity0 = new ChartEntity(rectangle0);
      chartEntity0.setToolTipText("");
      String string0 = chartEntity0.getToolTipText();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Polygon polygon0 = new Polygon();
      ChartEntity chartEntity0 = new ChartEntity(polygon0, "j6|h{JKh", "j6|h{JKh");
      String string0 = chartEntity0.getShapeCoords();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Line2D.Double line2D_Double0 = new Line2D.Double();
      ChartEntity chartEntity0 = new ChartEntity(line2D_Double0, "!p6h%Byf", "!p6h%Byf");
      // Undeclared exception!
      try { 
        chartEntity0.setArea((Shape) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Null 'area' argument.
         //
         verifyException("org.jfree.chart.internal.Args", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Polygon polygon0 = new Polygon();
      polygon0.npoints = 2208;
      ChartEntity chartEntity0 = new ChartEntity(polygon0, "%k*1Crc7Tbl", "%k*1Crc7Tbl");
      // Undeclared exception!
      try { 
        chartEntity0.getShapeCoords();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Line2D.Double line2D_Double0 = new Line2D.Double();
      ChartEntity chartEntity0 = new ChartEntity(line2D_Double0, " alt=\"\"", (String) null);
      DynamicDriveToolTipTagFragmentGenerator dynamicDriveToolTipTagFragmentGenerator0 = new DynamicDriveToolTipTagFragmentGenerator((String) null, 1);
      StandardURLTagFragmentGenerator standardURLTagFragmentGenerator0 = new StandardURLTagFragmentGenerator();
      // Undeclared exception!
      try { 
        chartEntity0.getImageMapAreaTag(dynamicDriveToolTipTagFragmentGenerator0, standardURLTagFragmentGenerator0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Null 'input' argument.
         //
         verifyException("org.jfree.chart.internal.Args", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Polygon polygon0 = new Polygon();
      polygon0.npoints = 2208;
      ChartEntity chartEntity0 = new ChartEntity(polygon0, "%k*1Crc7Tbl", "%k*1Crc7Tbl");
      StandardToolTipTagFragmentGenerator standardToolTipTagFragmentGenerator0 = new StandardToolTipTagFragmentGenerator();
      StandardURLTagFragmentGenerator standardURLTagFragmentGenerator0 = new StandardURLTagFragmentGenerator();
      // Undeclared exception!
      try { 
        chartEntity0.getImageMapAreaTag(standardToolTipTagFragmentGenerator0, standardURLTagFragmentGenerator0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ChartEntity chartEntity0 = null;
      try {
        chartEntity0 = new ChartEntity((Shape) null, "z DG", "z DG");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Null 'area' argument.
         //
         verifyException("org.jfree.chart.internal.Args", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ChartEntity chartEntity0 = null;
      try {
        chartEntity0 = new ChartEntity((Shape) null, "shape");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Null 'area' argument.
         //
         verifyException("org.jfree.chart.internal.Args", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ChartEntity chartEntity0 = null;
      try {
        chartEntity0 = new ChartEntity((Shape) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Null 'area' argument.
         //
         verifyException("org.jfree.chart.internal.Args", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Rectangle2D.Double rectangle2D_Double0 = new Rectangle2D.Double();
      ChartEntity chartEntity0 = new ChartEntity(rectangle2D_Double0);
      String string0 = chartEntity0.getShapeType();
      assertEquals("rect", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Line2D.Double line2D_Double0 = new Line2D.Double();
      ChartEntity chartEntity0 = new ChartEntity(line2D_Double0);
      String string0 = chartEntity0.getShapeType();
      assertEquals("poly", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Polygon polygon0 = new Polygon();
      ChartEntity chartEntity0 = new ChartEntity(polygon0, "j6|h{JKh", "j6|h{JKh");
      ChartEntity chartEntity1 = new ChartEntity(polygon0, "j6|h{JKh");
      boolean boolean0 = chartEntity0.equals(chartEntity1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Rectangle2D.Float rectangle2D_Float0 = new Rectangle2D.Float();
      Dimension dimension0 = new Dimension();
      Rectangle rectangle0 = new Rectangle(dimension0);
      Rectangle2D rectangle2D0 = rectangle2D_Float0.createUnion(rectangle0);
      ChartEntity chartEntity0 = new ChartEntity(rectangle2D_Float0, "aN@`H");
      ChartEntity chartEntity1 = new ChartEntity(rectangle2D0, "7l{!b|");
      boolean boolean0 = chartEntity0.equals(chartEntity1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Line2D.Double line2D_Double0 = new Line2D.Double();
      ChartEntity chartEntity0 = new ChartEntity(line2D_Double0, "W", "W");
      Line2D.Double line2D_Double1 = new Line2D.Double();
      ChartEntity chartEntity1 = new ChartEntity(line2D_Double1);
      boolean boolean0 = chartEntity0.equals(chartEntity1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Rectangle2D.Float rectangle2D_Float0 = new Rectangle2D.Float();
      ChartEntity chartEntity0 = new ChartEntity(rectangle2D_Float0, "aN@`H");
      Object object0 = chartEntity0.clone();
      boolean boolean0 = object0.equals(chartEntity0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Line2D.Double line2D_Double0 = new Line2D.Double();
      ChartEntity chartEntity0 = new ChartEntity(line2D_Double0, "", "");
      boolean boolean0 = chartEntity0.equals(chartEntity0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Rectangle2D.Float rectangle2D_Float0 = new Rectangle2D.Float();
      Dimension dimension0 = new Dimension();
      ChartEntity chartEntity0 = new ChartEntity(rectangle2D_Float0, "aN@`H");
      boolean boolean0 = chartEntity0.equals(dimension0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Line2D.Double line2D_Double0 = new Line2D.Double();
      ChartEntity chartEntity0 = new ChartEntity(line2D_Double0, "", "");
      OverLIBToolTipTagFragmentGenerator overLIBToolTipTagFragmentGenerator0 = new OverLIBToolTipTagFragmentGenerator();
      StandardURLTagFragmentGenerator standardURLTagFragmentGenerator0 = new StandardURLTagFragmentGenerator();
      String string0 = chartEntity0.getImageMapAreaTag(overLIBToolTipTagFragmentGenerator0, standardURLTagFragmentGenerator0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Line2D.Double line2D_Double0 = new Line2D.Double();
      ChartEntity chartEntity0 = new ChartEntity(line2D_Double0, (String) null, " coords=\"");
      OverLIBToolTipTagFragmentGenerator overLIBToolTipTagFragmentGenerator0 = new OverLIBToolTipTagFragmentGenerator();
      StandardURLTagFragmentGenerator standardURLTagFragmentGenerator0 = new StandardURLTagFragmentGenerator();
      String string0 = chartEntity0.getImageMapAreaTag(overLIBToolTipTagFragmentGenerator0, standardURLTagFragmentGenerator0);
      assertEquals("<area shape=\"poly\" coords=\"0,0,0,0\" href=\" coords=\"\" alt=\"\"/>", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Rectangle2D.Float rectangle2D_Float0 = new Rectangle2D.Float();
      ChartEntity chartEntity0 = new ChartEntity(rectangle2D_Float0, "aN@`H");
      DynamicDriveToolTipTagFragmentGenerator dynamicDriveToolTipTagFragmentGenerator0 = new DynamicDriveToolTipTagFragmentGenerator();
      StandardURLTagFragmentGenerator standardURLTagFragmentGenerator0 = new StandardURLTagFragmentGenerator();
      String string0 = chartEntity0.getImageMapAreaTag(dynamicDriveToolTipTagFragmentGenerator0, standardURLTagFragmentGenerator0);
      assertEquals("<area shape=\"rect\" coords=\"0,0,1,1\" onMouseOver=\"return stm(['','aN@`H'],Style[1]);\" onMouseOut=\"return htm();\" nohref=\"nohref\"/>", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Rectangle rectangle0 = new Rectangle((-1932735280), 2746);
      ChartEntity chartEntity0 = new ChartEntity(rectangle0);
      String string0 = chartEntity0.getShapeCoords();
      assertEquals("0,0,-1932735280,2746", string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      StandardURLTagFragmentGenerator standardURLTagFragmentGenerator0 = new StandardURLTagFragmentGenerator();
      Rectangle2D.Double rectangle2D_Double0 = new Rectangle2D.Double();
      ChartEntity chartEntity0 = new ChartEntity(rectangle2D_Double0, "%k*1Crc7Tbl", "");
      // Undeclared exception!
      try { 
        chartEntity0.getImageMapAreaTag((ToolTipTagFragmentGenerator) null, standardURLTagFragmentGenerator0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jfree.chart.entity.ChartEntity", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Point point0 = new Point(0, 6);
      Line2D.Double line2D_Double0 = new Line2D.Double(point0, point0);
      ChartEntity chartEntity0 = new ChartEntity(line2D_Double0, "j6|h{JKh");
      chartEntity0.setURLText("");
      assertEquals("j6|h{JKh", chartEntity0.getToolTipText());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Polygon polygon0 = new Polygon();
      ChartEntity chartEntity0 = new ChartEntity(polygon0, "ChartEntity: ");
      Shape shape0 = chartEntity0.getArea();
      assertSame(shape0, polygon0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Polygon polygon0 = new Polygon();
      ChartEntity chartEntity0 = new ChartEntity(polygon0);
      chartEntity0.setURLText("51b^teiZ{7jH0_{' ");
      String string0 = chartEntity0.getURLText();
      assertEquals("51b^teiZ{7jH0_{' ", string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Rectangle2D.Double rectangle2D_Double0 = new Rectangle2D.Double();
      ChartEntity chartEntity0 = new ChartEntity(rectangle2D_Double0, "%k*1Crc7Tbl", "");
      String string0 = chartEntity0.getURLText();
      assertEquals("%k*1Crc7Tbl", chartEntity0.getToolTipText());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Point point0 = new Point(0, 6);
      Line2D.Double line2D_Double0 = new Line2D.Double(point0, point0);
      ChartEntity chartEntity0 = new ChartEntity(line2D_Double0, "j6|h{JKh");
      String string0 = chartEntity0.getToolTipText();
      assertEquals("j6|h{JKh", string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Point point0 = new Point(0, 6);
      Line2D.Double line2D_Double0 = new Line2D.Double(point0, point0);
      ChartEntity chartEntity0 = new ChartEntity(line2D_Double0, "j6|h{JKh");
      chartEntity0.hashCode();
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Rectangle2D.Double rectangle2D_Double0 = new Rectangle2D.Double();
      ChartEntity chartEntity0 = new ChartEntity(rectangle2D_Double0, "%k*1Crc7Tbl", "");
      chartEntity0.setArea(rectangle2D_Double0);
      assertEquals("%k*1Crc7Tbl", chartEntity0.getToolTipText());
      assertEquals("", chartEntity0.getURLText());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Point point0 = new Point(0, 6);
      Line2D.Double line2D_Double0 = new Line2D.Double(point0, point0);
      ChartEntity chartEntity0 = new ChartEntity(line2D_Double0, "j6|h{JKh");
      String string0 = chartEntity0.toString();
      assertEquals("ChartEntity: tooltip = j6|h{JKh", string0);
  }
}
