/*
 * This file was automatically generated by EvoSuite
 * Mon May 31 16:35:54 GMT 2021
 */

package org.jfree.chart;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.Paint;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jfree.chart.ChartColor;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ChartColor_ESTest extends ChartColor_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ChartColor chartColor0 = new ChartColor(0, 0, 59);
      assertEquals((-16777157), chartColor0.getRGB());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ChartColor chartColor0 = null;
      try {
        chartColor0 = new ChartColor((-12), (-12), (-12));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Color parameter outside of expected range: Red Green Blue
         //
         verifyException("java.awt.Color", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Paint[] paintArray0 = ChartColor.createDefaultPaintArray();
      assertEquals(34, paintArray0.length);
  }
}
