/*
 * This file was automatically generated by EvoSuite
 * Mon May 31 17:02:54 GMT 2021
 */

package org.jfree.chart;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jfree.chart.ChartHints;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ChartHints_ESTest extends ChartHints_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ChartHints.Key chartHints_Key0 = ChartHints.KEY_END_ELEMENT;
      Object object0 = new Object();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ChartHints.Key chartHints_Key0 = new ChartHints.Key(3560);
  }
}
